const events = [
{ event: "James Watt erfindet die erste Dampfmaschine", year: 1769 },
{ event: "Nikolaus Otto erfindet den Verbrennungsmotor", year: 1876 },
{ event: "Alexander Graham Bell erfindet das Telefon", year: 1876 },
{ event: "Edward Jenner entwickelt die erste Impfung gegen Pocken", year: 1796 },
{ event: "Thomas Edison entwickelt die erste praxistaugliche Glühbirne", year: 1879 },
{ event: "Ralph Baer entwickelt die erste Videospielkonsole", year: 1972 },
{ event: "Steve Jobs präsentiert das erste moderne Smartphone (iPhone)", year: 2007 },
{ event: "Samuel Morse erfindet den ersten Morse-Apparat", year: 1837 },
{ event: "Wilhelm Conrad Röntgen entdeckt die Röntgenstrahlen", year: 1895 },
{ event: "Alexander Fleming entdeckt das erste Antibiotikum (Penicillin)", year: 1928 },
{ event: "Albert Einstein formuliert die Spezielle Relativitätstheorie", year: 1905 },
{ event: "Karl Benz baut das erste Auto mit Verbrennungsmotor", year: 1866 },
{ event: "Alva J. Fisher baut die erste elektrische Waschmaschine", year: 1908 },
{ event: "Douglas Engelbart erfindet die erste Computermaus", year: 1964 },
{ event: "J.J. Thomson entdeckt das Elektron", year: 1897 },
{ event: "Bill Gates und Paul Allen gründen Microsoft", year: 1975 },
{ event: "Jeff Bezos gründet Amazon", year: 1994 },
{ event: "Mark Zuckerberg gründet Meta (ehemals Facebook)", year: 2004 },
{ event: "Jensen Huang, Chris Malachowsky und Curtis Priem gründen Nvidia", year: 1993 },
{ event: "Elon Musk gründet Tesla, Inc.", year: 2003 },
{ event: "George de Mestral erfindet den Klettverschluss", year: 1948 },
{ event: "Thierry Hermès gründet Hermès", year: 1837 },
{ event: "Lee Byung‑chul gründet Samsung", year: 1938 },
{ event: "Bernard Arnault gründet LVMH", year: 1987 },
{ event: "Katalin Karikó und Drew Weissman legen die Basis für die mRNA-Impfstofftechnologie", year: 2005 },
{ event: "Jack Ma gründet Alibaba", year: 1999 },
{ event: "Heinrich Nestlé gründet Nestlé", year: 1866 },
{ event: "Sol Price gründet Costco", year: 1976 },
{ event: "Ajay Banga gründet Mastercard", year: 1966 },
{ event: "Die Bundesrepublik Deutschland gründet die neue Lufthansa als Nachfolger der alten Fluglinie", year: 1953 },
{ event: "Ferdinand Porsche und die NS-Regierung gründen Volkswagen", year: 1937 },
{ event: "Theodore Roosevelt wird US-Präsident", year: 1901 },
{ event: "Abraham Lincoln wird US-Präsident", year: 1861 },
{ event: "John F. Kennedy wird US-Präsident", year: 1961 },
{ event: "Richard Nixon wird US-Präsident", year: 1969 },
{ event: "Ronald Reagan wird US-Präsident", year: 1981 },
{ event: "Bill Clinton wird US-Präsident", year: 1993 },
{ event: "Barrack Obama wird US-Präsident", year: 2009 },
{ event: "Donald Trump wird erstmals US-Präsident", year: 2017 },
{ event: "George Washington wird erster US-Präsident", year: 1789 },
{ event: "Adolf Hitler wird Reichskanzler des Deutschen Reichs", year: 1933 },
{ event: "Konrad Adenauer wird erster Bundeskanzler der Bundesrepublik Deutschland", year: 1949 },
{ event: "Angela Merkel wird Bundeskanzlerin der Bundesrepublik Deutschland", year: 2005 },
{ event: "Xi Jinping wird Generalsekretär der Kommunistischen Partei Chinas", year: 2012 },
{ event: "Wladimir Putin wird erstmals Präsident der Russischen Föderation", year: 1999 },
{ event: "Mao Zedong wird Vorsitzender der Kommunistischen Partei Chinas und Staatsführer", year: 1949 },
{ event: "Josef Stalin wird Generalsekretär der KPdSU und de-facto Führer der Sowjetunion", year: 1922 },
{ event: "Der 1. Weltkrieg beginnt", year: 1914 },
{ event: "Der 2. Weltkrieg beginnt mit dem Überfall auf Polen", year: 1939 },
{ event: "Die Vereinten Nationen (UN) werden gegründet", year: 1945 },
{ event: "Der Koreakrieg beginnt", year: 1950 },
{ event: "Die Berliner Mauer fällt", year: 1989 },
{ event: "Indien wird von Großbritannien unabhängig", year: 1947 },
{ event: "Großbritannien stimmt im Brexit-Referendum für den EU-Austritt", year: 2016 },
{ event: "Der Arabische Frühling beginnt in Tunesien", year: 2010 },
{ event: "Anhänger von Donald Trump stürmen das US-Kapitol", year: 2021 },
{ event: "Die NATO wird gegründet", year: 1949 },
{ event: "Der Staat Israel wird ausgerufen", year: 1948 },
{ event: "Das Pariser Klimaabkommen wird beschlossen", year: 2015 },
{ event: "Das Tian’anmen-Massaker erschüttert Peking", year: 1989 },
{ event: "Russland beginnt den vollständigen Angriffskrieg gegen die Ukraine", year: 2022 },
{ event: "Der Vertrag von Maastricht begründet die Europäische Union", year: 1992 },
{ event: "Der Euro wird als Bargeld eingeführt", year: 2002 },
{ event: "Jimi Hendrix entzündet bei Woodstock seine Gitarre", year: 1969 },
{ event: "Peter Tschaikowskys „Schwanensee“ wird uraufgeführt", year: 1877 },
{ event: "Daniel Ek und Martin Lorentzon gründen Spotify", year: 2006 },
{ event: "The Rolling Stones spielen im Hyde Park vor über 250.000 Menschen", year: 1969 },
{ event: "ABBA gewinnen den Eurovision Song Contest mit „Waterloo“", year: 1974 },
{ event: "Michael Jackson tanzt den Moonwalk live im US-TV", year: 1983 },
{ event: "MTV geht auf Sendung mit „Video Killed the Radio Star“", year: 1981 },
{ event: "Live Aid bringt die Welt via Musik zusammen", year: 1985 },
{ event: "Die erste MP3-Datei wird offiziell veröffentlicht", year: 1995 },
{ event: "Apple startet den iTunes Store und revolutioniert den Musikvertrieb", year: 2003 },
{ event: "Psy erreicht mit „Gangnam Style“ auf YouTube als erster Künstler 1 Milliarde Views", year: 2012 },
{ event: "Billie Eilish gewinnt mit 18 alle vier Haupt-Grammys", year: 2020 },
{ event: "Michael Jackson veröffentlicht mit „Thriller“ das meistverkaufte Album aller Zeiten", year: 1982 },
{ event: "„Despacito“ von Luis Fonsi erreicht als erstes Video 7 Milliarden YouTube-Views", year: 2020 },
{ event: "Drake hat mit 27 Songs gleichzeitig in den Billboard Hot 100 einen Allzeit-Rekord", year: 2018 },
{ event: "Andrea Bocelli singt mit über 2,8 Millionen Livestream-Zuschauern zu Ostern aus dem leeren Mailänder Dom", year: 2020 },
{ event: "John Lennon wird in New York erschossen", year: 1980 },
{ event: "Die Brüder Lumière führen in Paris den ersten öffentlichen Film vor", year: 1895 },
{ event: "Charlie Chaplin feiert mit „The Kid“ seinen ersten Langfilm-Erfolg", year: 1921 },
{ event: "Walt Disney veröffentlicht mit „Steamboat Willie“ den ersten Mickey-Mouse-Film", year: 1928 },
{ event: "Die Oscars werden erstmals im Fernsehen übertragen", year: 1953 },
{ event: "„Ben Hur“ gewinnt mit 11 Oscars erstmals die Rekordmarke", year: 1959 },
{ event: "„Star Trek“ (Raumschiff Enterprise) feiert TV-Premiere in den USA", year: 1966 },
{ event: "„Star Wars“ kommt erstmals in die Kinos und löst einen weltweiten Hype aus", year: 1977 },
{ event: "„Das Boot“ wird zur teuersten deutschen TV-Produktion", year: 1981 },
{ event: "Netflix startet sein Streaming-Angebot in den USA", year: 2007 },
{ event: "„Avatar“ sprengt als 3D-Kinofilm alle Einnahmerekorde", year: 2009 },
{ event: "„Squid Game“ wird zur meistgesehenen Netflix-Serie weltweit", year: 2021 },
{ event: "„Parasite“ gewinnt als erster fremdsprachiger Film den Oscar für „Best Picture“", year: 2020 },
{ event: "Heath Ledger begeistert posthum als Joker in „The Dark Knight“", year: 2008 },
{ event: "„Der Herr der Ringe: Die Gefährten“ kommt erstmals in die Kinos", year: 2001 },
{ event: "Hattie McDaniel wird als erste Afroamerikanerin mit einem Oscar ausgezeichnet", year: 1940 },
{ event: "Hollywood wird durch den Weinstein-Skandal und die #MeToo-Bewegung erschüttert", year: 2017 },
{ event: "Das erste internationale Wimbledon-Turnier findet statt", year: 1877 },
{ event: "FIFA wird als Weltfußballverband gegründet", year: 1904 },
{ event: "Die Tour de France wird zum ersten Mal ausgetragen", year: 1903 },
{ event: "Die Formel 1 startet mit ihrer ersten Weltmeisterschaftssaison", year: 1950 },
{ event: "Das erste NBA-Spiel wird gespielt", year: 1946 },
{ event: "Die NFL wird gegründet", year: 1920 },
{ event: "Die erste Fußball-Weltmeisterschaft beginnt in Uruguay", year: 1930 },
{ event: "Jesse Owens gewinnt vier Goldmedaillen bei den Nazi-Spielen in Berlin", year: 1936 },
{ event: "Usain Bolt sprintet Weltrekord über 100 m in 9,58 s", year: 2009 },
{ event: "Michael Phelps gewinnt acht Goldmedaillen bei den Spielen von Peking", year: 2008 },
{ event: "Die Olympischen Spiele in München werden von einem Terroranschlag überschattet", year: 1972 },
{ event: "Tiger Woods gewinnt als erster Schwarzer das US Masters im Golf", year: 1997 },
{ event: "Die deutsche Basketball-Nationalmannschaft wird erstmals Weltmeister", year: 2023 },
{ event: "Tom Brady gewinnt seinen 7. Super Bowl – mit 43 Jahren", year: 2021 },
{ event: "Pelé wird mit 17 Jahren der jüngste WM-Finaltorschütze", year: 1958 },
{ event: "Brasilien verliert das Heim-Halbfinale der WM mit 1:7 gegen Deutschland", year: 2014 },
{ event: "Ein Erdbeben in Fukushima mit anschließender Atomkatastrophe erschüttert Japan", year: 2011 },
{ event: "Das Erdbeben von Haiti fordert über 200.000 Menschenleben", year: 2010 },
{ event: "Ein Tsunami trifft Lissabon nach schwerem Beben", year: 1755 },
{ event: "Die Atombombe zerstört Hiroshima", year: 1945 },
{ event: "Die Atombombe trifft Nagasaki", year: 1945 },
{ event: "Der Vietnamkrieg mit US-Einmischung beginnt", year: 1964 },
{ event: "Der Angriff auf das World Trade Center erschüttert die Welt", year: 2001 },
{ event: "Die Spanische Grippe bricht aus", year: 1918 },
{ event: "Die Covid-19-Pandemie beginnt", year: 2020 },
{ event: "Ebola bricht in Westafrika aus", year: 2014 },
{ event: "HIV/AIDS wird zur globalen Pandemie", year: 1981 },
{ event: "Der Untergang der Titanic kostet über 1.500 Menschen das Leben", year: 1912 },
{ event: "Die Reaktorkatastrophe von Tschernobyl verseucht weite Teile Europas", year: 1986 },
{ event: "Die Bhopal-Katastrophe ereignet sich in Indien", year: 1984 },
{ event: "Der Rwandische Völkermord beginnt", year: 1994 },
{ event: "Das Loveparade-Unglück in Duisburg fordert 21 Tote", year: 2010 },
{ event: "Ägypten wird vom Vereinigten Königreich unabhängig", year: 1922 },
{ event: "Algerien erlangt die Unabhängigkeit von Frankreich", year: 1962 },
{ event: "Afghanistan wird vom Vereinigten Königreich unabhängig", year: 1919 },
{ event: "Vietnam erklärt Unabhängigkeit von Frankreich", year: 1945 },
{ event: "Haiti wird als erster unabhängiger Staat schwarzer Sklaven gegründet", year: 1804 },
{ event: "Brasilien erklärt seine Unabhängigkeit von Portugal", year: 1822 },
{ event: "Ukraine wird nach Zerfall der Sowjetunion unabhängig", year: 1991 },
{ event: "Tschechien wird mit der „Samtenen Scheidung“ unabhängig von der Slowakei", year: 1993 },
{ event: "Norwegen trennt sich von Schweden und wird unabhängig", year: 1905 },
{ event: "Kroatien wird nach Zerfall Jugoslawiens unabhängig", year: 1991 },
{ event: "Nigeria wird unabhängig vom Vereinigten Königreich", year: 1960 },
{ event: "Demokratische Republik Kongo wird von Belgien unabhängig", year: 1960 },
{ event: "Südafrika wird offiziell unabhängig vom Vereinigten Königreich", year: 1961 },
{ event: "Die DDR (Deutsche Demokratische Republik) wird gegründet", year: 1949 },
{ event: "Kosovo erklärt einseitig die Unabhängigkeit von Serbien", year: 2008 },
{ event: "Irland wird nach Unabhängigkeitskrieg vom Vereinigten Königreich unabhängig", year: 1922 },
{ event: "Abraham Lincoln wird im Theater von John Wilkes Booth erschossen", year: 1865 },
{ event: "Mahatma Gandhi wird von einem Nationalisten erschossen", year: 1948 },
{ event: "John F. Kennedy wird in Dallas von Lee Harvey Oswald erschossen", year: 1963 },
{ event: "Martin Luther King Jr. wird in Memphis erschossen", year: 1968 },
{ event: "Alexander II. von Russland stirbt durch eine Bombe von Anarchisten", year: 1881 },
{ event: "Zoran Đinđić, Premier Serbiens, wird in Belgrad erschossen", year: 2003 },
{ event: "Malcolm X wird während einer Rede erschossen", year: 1965 },
{ event: "Tupac Shakur wird bei einem Drive-by-Shooting in Las Vegas erschossen", year: 1996 },
{ event: "Kim Jong-nam, Halbbruder von Kim Jong-un, wird mit Nervengift ermordet", year: 2017 },
{ event: "Shinzo Abe, ehemaliger Premierminister Japans, wird bei einer Rede erschossen", year: 2022 },
{ event: "Marilyn Monroe stirbt an einer Überdosis", year: 1962 },
{ event: "Kurt Cobain erschießt sich mit einer Schrotflinte", year: 1994 },
{ event: "Chester Bennington, Sänger von Linkin Park, erhängt sich – am Geburtstag seines Freundes Chris Cornell", year: 2017 },
{ event: "Stefan Zweig begeht mit seiner Frau Suizid im brasilianischen Exil", year: 1942 },
{ event: "Avicii nimmt sich im Oman das Leben", year: 2018 },
{ event: "Juice WRLD stirbt nach einer versehentlichen Überdosis", year: 2019 },
{ event: "Der Tempel Salomos wird in Jerusalem fertiggestellt", year: -957 },
{ event: "Die erste Olympiade der Antike findet in Griechenland statt", year: -776 },
{ event: "Julius Cäsar wird ermordet (Iden des März)", year: -44 },
{ event: "Jesus von Nazareth wird (vermutlich) gekreuzigt", year: 30 },
{ event: "Der Prophet Mohammed flieht aus Mekka nach Medina (Hedschra)", year: 622 },
{ event: "Karl der Große wird Kaiser des Heiligen Römischen Reichs", year: 800 },
{ event: "Die Erste Kreuzzug beginnt nach Aufruf von Papst Urban II.", year: 1096 },
{ event: "Der Schwarze Tod (Pest) erreicht Europa", year: 1347 },
{ event: "Johannes Gutenberg erfindet den Buchdruck mit beweglichen Lettern", year: 1450 },
{ event: "Martin Luther schlägt seine 95 Thesen an die Kirchentür in Wittenberg", year: 1517 },
{ event: "Leonardo da Vinci stellt das „Abendmahl“ fertig", year: 1498 },
{ event: "Die Pyramide von Gizeh wird vollendet", year: -2560 },
{ event: "Die Normannen erobern England (Schlacht bei Hastings)", year: 1066 },
{ event: "Die Große Mauer in China wird unter Qin Shi Huang begonnen", year: -220 },
{ event: "Die Hagia Sophia wird in Konstantinopel eingeweiht", year: 537 },
{ event: "Alexander der Große wird König von Makedonien", year: -336 },
{ event: "Vincent van Gogh schneidet sich nach Streit mit Gauguin das Ohr ab", year: 1888 },
{ event: "„Guernica“ von Picasso wird auf der Pariser Weltausstellung enthüllt", year: 1937 },
{ event: "Banksy sprengt Kunstmarkt mit geschreddertem Bild „Girl with Balloon“ bei Sotheby’s", year: 2018 },
{ event: "„Der Wanderer über dem Nebelmeer“ von Caspar David Friedrich wird fertiggestellt", year: 1818 },
{ event: "Künstler Ai Weiwei wird in China inhaftiert", year: 2011 },
{ event: "Leonardo da Vincis „Salvator Mundi“ wird für 450 Mio. Dollar versteigert", year: 2017 },
{ event: "Das „Musée du Louvre“ öffnet als erstes großes öffentliches Kunstmuseum", year: 1793 },
{ event: "„Der Schrei“ von Edvard Munch wird aus dem Osloer Museum gestohlen", year: 2004 },
{ event: "Der Kunstfälscher Wolfgang Beltracchi fliegt auf", year: 2010 },
{ event: "Das Bauhaus wird von Walter Gropius in Weimar gegründet", year: 1919 },
{ event: "NFT-Kunstwerk von Beeple („Everydays“) wird für 69 Mio.  Dollar verkauft", year: 2021 },
{ event: "Die erste Biennale in Venedig findet statt", year: 1895 },
{ event: "Die Tate Modern in London wird eröffnet", year: 2000 },
{ event: "Das Museum of Modern Art (MoMA) wird in New York eröffnet", year: 1929 },
{ event: "Auguste Rodin vollendet die erste Gussfassung von „Der Denker“", year: 1902 },
{ event: "Edvard Munch malt „Der Schrei“", year: 1893 },
{ event: "Insulin wird durch Versuche an Hunden entdeckt", year: 1921 },
{ event: "Das GIF-Format wird für Wetterkarten entwickelt", year: 1987 },
{ event: "Das erste SMS wird mit „Merry Christmas“ von einem Computer an ein Handy geschickt", year: 1992 },
{ event: "Das erste Live-Fernsehbild wird in Deutschland übertragen", year: 1935 },
{ event: "Die erste Tonaufnahme der Welt ist ein französisches Kinderlied „Au clair de la lune“ auf Rußpapier", year: 1860 },
{ event: "Die erste Werbung im Radio war für ein Wohnbauprojekt in New York", year: 1922 },
{ event: "Das erste lebende Tier, ein Schaf namens Dolly, wird geklont", year: 1996 },
{ event: "Die erste künstliche Zelle wird von Craig Venter erzeugt", year: 2010 },
{ event: "Die Braille-Schrift wird von einem blinden Teenager in Frankreich erfunden", year: 1825 },
{ event: "Der Bikini wird kurz nach dem ersten Atombombentest „Bikini Atoll“ benannt", year: 1946 },
{ event: "Das „@“-Zeichen wird für E-Mails recycelt – aus dem Buchhaltungswesen des Mittelalters", year: 1971 },
{ event: "Die Thermoskanne wird in Jena für Laborversuche entwickelt", year: 1892 },
{ event: "Der Urknall wird durch ein störendes Rauschen in einer Antenne nachgewiesen", year: 1964 },
{ event: "Die DNA-Struktur wird durch Rosalind Franklin sichtbar gemacht", year: 1953 },
{ event: "Teflon entsteht bei einem fehlgeschlagenen Experiment mit Kühlgasen bei DuPont", year: 1938 },
{ event: "Das Internet entsteht aus einem Militärprojekt zur Datenweitergabe im Kalten Krieg (ARPANET)", year: 1969 },
{ event: "Nelson Mandela wird freigelassen", year: 1990 },
{ event: "Mahatma Gandhi beginnt den Salzmarsch", year: 1930 },
{ event: "Die Frauen erhalten in der Schweiz das Wahlrecht", year: 1971 },
{ event: "Greta Thunberg startet ihren ersten Klimastreik", year: 2018 },
{ event: "Der Amerikanische Bürgerkrieg beginnt", year: 1861 },
{ event: "Der Koreakrieg beginnt", year: 1950 },
{ event: "Die erste Herztransplantation gelingt in Südafrika", year: 1967 },
{ event: "Die künstliche Intelligenz „Deep Blue“ besiegt den Schachweltmeister Garry Kasparov", year: 1997 },
{ event: "China führt die Ein-Kind-Politik ein", year: 1980 },
{ event: "Das erste Mobiltelefon-Gespräch wird geführt", year: 1973 },
{ event: "Elon Musk startet mit SpaceX die erste private bemannte Mission ins All", year: 2020 },
{ event: "Die Wikipedia wird gegründet", year: 2001 },
{ event: "Google geht online", year: 1998 },
{ event: "ChatGPT wird öffentlich zugänglich gemacht", year: 2022 },
{ event: "Der Large Hadron Collider (CERN) wird in Betrieb genommen", year: 2008 },
{ event: "In New York fließt der erste elektrische Strom im öffentlichen Stromnetz", year: 1882 },
];
